name: taptapfirebase
description: "Tap Tap Firebase Project"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-42.2.beta <4.0.0"

dependencies:
  cloud_firestore: ^4.9.1
  dartz: ^0.10.1
  device_info_plus: ^9.0.3
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  riverpod: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
